export const drafts = [
    'abelha', 'águia', 'alce', 'alpaca', 'anta', 'aranha', 'avestruz', 'baleia',
    'barata', 'beija-flor', 'boi', 'borboleta', 'boto', 'burro', 'cabra',
    'cachorro', 'calango', 'camaleão', 'camarão', 'camelo', 'camundongo',
    'canguru', 'capivara', 'caracol', 'caranguejo', 'carneiro', 'castor',
    'cavalo', 'cavalo-marinho', 'cobra', 'coelho', 'coruja', 'crocodilo',
    'dragão-de-comodo', 'elefante', 'esquilo', 'foca', 'formiga', 'galinha',
    'galo', 'gambá', 'garça', 'gato', 'gavião', 'girafa', 'golfinho', 'gorila',
    'guaxinim', 'hamster', 'hipopótamo', 'hiena', 'iguana', 'jabuti', 'jacaré',
    'jaguar', 'joaninha', 'joão-de-barro', 'koala', 'lagarta', 'lagarto',
    'leão', 'leão-marinho', 'lesma', 'lhama', 'libélula', 'lobo', 'lontra',
    'macaco', 'morcego', 'mosca', 'onça', 'orangotango', 'ovelha', 'panda',
    'papagaio', 'pato', 'pavão', 'peixe', 'peixe-boi', 'pelicano', 'pinguim',
    'polvo', 'porco', 'porco-espinho', 'preguiça', 'rato', 'rinoceronte',
    'sapo', 'serpente', 'tartaruga', 'tatu', 'tigre', 'touro', 'tucano',
    'urso', 'vaca', 'veado', 'zebra',

    // Objetos e Utensílios
    'abajur', 'agulha', 'alfinete', 'almofada', 'anel', 'antena', 'apagador',
    'apontador', 'armário', 'aspirador', 'banco', 'bandeja', 'bengala',
    'berço', 'bicicleta', 'bidê', 'binóculo', 'bolsa', 'boneca', 'bota',
    'botão', 'brinco', 'bronze', 'cabide', 'cadeira', 'caderno', 'caixa',
    'calculadora', 'cama', 'câmera', 'caneca', 'caneta', 'canga', 'cinto',
    'chave', 'chinelo', 'chuveiro', 'colher', 'copo', 'coroa', 'corrente',
    'cruz', 'dado', 'dardo', 'dedal', 'dentadura', 'desenho', 'despertador',
    'dicionário', 'disco', 'escada', 'escova', 'espada', 'espanador', 'espelho',
    'estante', 'faca', 'filtro', 'fita', 'fogão', 'foice', 'folha', 'foto',
    'frigideira', 'funil', 'gaita', 'gancho', 'garfo', 'garrafa', 'gaveta',
    'geladeira', 'giz', 'grampeador', 'guarda-chuva', 'guitarra', 'harpa',
    'hélice', 'isqueiro', 'janela', 'jarra', 'jornal', 'lâmpada', 'lápis',
    'lapiseira', 'lenço', 'lençol', 'liquidificador', 'livro', 'lixeira',
    'luva', 'machado', 'mala', 'martelo', 'máscara', 'medalha', 'mesa',
    'microfone', 'microscópio', 'moeda', 'mola', 'monitor', 'mouse', 'mochila',
    'notebook', 'óculos', 'panela', 'papel', 'pasta', 'pente', 'pergaminho',
    'piano', 'pincel', 'pipa', 'pistola', 'porta', 'prato', 'prateleira',
    'quadro', 'rádio', 'ralador', 'régua', 'relógio', 'remo', 'revista',
    'rolha', 'sabonete', 'saca-rolhas', 'sacola', 'sandália', 'sapato',
    'serra', 'sofá', 'talher', 'tambor', 'tampa', 'tapete', 'teclado',
    'telefone', 'televisão', 'tesoura', 'tigela', 'toalha', 'torneira',
    'travesseiro', 'trompete', 'urna', 'vassoura', 'vela', 'ventilador',
    'violão', 'violino', 'xícara',

    // Alimentos e Bebidas
    'abacate', 'abacaxi', 'abóbora', 'abobrinha', 'açaí', 'acelga', 'achocolatado',
    'açúcar', 'agrião', 'água', 'alface', 'alho', 'ameixa', 'amendoim', 'amora',
    'arroz', 'aspargo', 'bacon', 'banana', 'batata', 'berinjela', 'beterraba',
    'biscoito', 'bolo', 'brigadeiro', 'brócolis', 'café', 'cajá', 'caju',
    'caqui', 'carambola', 'carne', 'castanha', 'cenoura', 'cereja', 'cerveja',
    'chá', 'chocolate', 'coco', 'cogumelo', 'couve', 'coxinha', 'creme',
    'damasco', 'empada', 'ervilha', 'espinafre', 'feijoada', 'figo', 'framboesa',
    'frango', 'goiaba', 'hambúrguer', 'hot-dog', 'iogurte', 'jabuticaba',
    'jaca', 'jambo', 'kiwi', 'laranja', 'leite', 'limão', 'linguiça',
    'maçã', 'macaxeira', 'mamão', 'manga', 'maracujá', 'margarina', 'melancia',
    'melão', 'mexerica', 'milho', 'morango', 'mortadela', 'mostarda', 'noz',
    'ovo', 'pão', 'pastel', 'pêra', 'pêssego', 'pipoca', 'pizza', 'pudim',
    'queijo', 'quiabo', 'rapadura', 'repolho', 'romã', 'salada', 'salsicha',
    'sopa', 'sorvete', 'suco', 'suspiro', 'tangerina', 'tapioca', 'tomate',
    'torta', 'uva', 'vagem', 'yakisoba',

    // Lugares e Construções
    'aeroporto', 'apartamento', 'aquário', 'armazém', 'banco', 'bar',
    'biblioteca', 'boate', 'boutique', 'cabana', 'cachoeira', 'cadeia',
    'cafeteria', 'castelo', 'catedral', 'caverna', 'cinema', 'circo',
    'clube', 'condomínio', 'corredor', 'escola', 'estacionamento', 'estádio',
    'estação', 'fábrica', 'farmácia', 'fazenda', 'feira', 'floresta',
    'fonte', 'forte', 'galeria', 'garagem', 'ginásio', 'gruta', 'hangar',
    'hotel', 'igreja', 'jardim', 'laboratório', 'lago', 'lanchonete',
    'livraria', 'loja', 'mansão', 'mercado', 'mesquita', 'metrô', 'moinho',
    'montanha', 'monumento', 'museu', 'navio', 'obra', 'oficina', 'padaria',
    'palácio', 'parque', 'piscina', 'planeta', 'ponte', 'porto', 'posto',
    'praça', 'praia', 'prefeitura', 'prisão', 'prédio', 'quadra', 'quartel',
    'quiosque', 'restaurante', 'rio', 'rodovia', 'shopping', 'templo',
    'teatro', 'túnel', 'universidade', 'vila', 'vulcão', 'zoológico',

    // Vestuário e Acessórios
    'agasalho', 'aliança', 'avental', 'bandana', 'bermuda', 'biquíni', 'blazer',
    'blusa', 'boina', 'boné', 'bota', 'botina', 'cachecol', 'calcinha',
    'calça', 'camisa', 'camiseta', 'camisola', 'capacete', 'capa', 'casaco',
    'chapéu', 'chinelo', 'cinto', 'colete', 'coroa', 'colar', 'cueca',
    'faixa', 'gravata', 'jaqueta', 'lenço', 'luva', 'macacão', 'maiô',
    'meia', 'moletom', 'paletó', 'pijama', 'pulôver', 'saia', 'sandália',
    'short', 'smoking', 'sobretudo', 'suéter', 'sunga', 'suspensório',
    'terno', 'tiara', 'touca', 'vestido',

    // Meios de Transporte
    'ambulância', 'avião', 'balão', 'barco', 'bicicleta', 'bondinho',
    'caminhão', 'canoa', 'carro', 'charrete', 'drone', 'escuna', 'foguete',
    'helicóptero', 'jangada', 'jato', 'jetski', 'kombi', 'lancha', 'locomotiva',
    'metrô', 'micro-ônibus', 'moto', 'navio', 'ônibus', 'patinete', 'patins',
    'planador', 'skate', 'submarino', 'trator', 'trem', 'triciclo', 'van',

    // Profissões
    'advogado', 'arqueólogo', 'arquiteto', 'artista', 'astronauta', 'atleta',
    'ator', 'bailarino', 'bombeiro', 'carteiro', 'chef', 'cientista',
    'dentista', 'detetive', 'eletricista', 'empresário', 'enfermeiro',
    'engenheiro', 'escritor', 'fazendeiro', 'fotógrafo', 'garçom', 'jardineiro',
    'jogador', 'juiz', 'maestro', 'marceneiro', 'mecânico', 'médico',
    'mergulhador', 'militar', 'motorista', 'músico', 'padeiro', 'palhaço',
    'pedreiro', 'pescador', 'piloto', 'pintor', 'policial', 'professor',
    'programador', 'repórter', 'soldado', 'vendedor', 'veterinário',

    // Elementos da Natureza
    'arco-íris', 'aurora', 'chuva', 'cometa', 'constelação', 'eclipse',
    'estrela', 'fogo', 'furacão', 'galaxia', 'gelo', 'lago', 'lua', 'mar',
    'meteoro', 'montanha', 'neve', 'nuvem', 'oceano', 'planeta', 'praia',
    'raio', 'rio', 'sol', 'terra', 'tornado', 'tsunami', 'vale', 'vulcão',

    // Esportes e Jogos
    'arco-e-flecha', 'badminton', 'basquete', 'beisebol', 'bilhar', 'boliche',
    'boxe', 'capoeira', 'ciclismo', 'dama', 'dardo', 'dominó', 'esgrima',
    'futebol', 'ginástica', 'golfe', 'handebol', 'hockey', 'judo', 'karatê',
    'natação', 'patinação', 'pesca', 'ping-pong', 'poker', 'polo', 'rugby',
    'sinuca', 'surfe', 'tênis', 'vôlei', 'xadrez',

    // Instrumentos Musicais
    'acordeão', 'agogô', 'bateria', 'berimbau', 'cavaquinho', 'chocalho',
    'clarinete', 'contrabaixo', 'corneta', 'cuíca', 'flauta', 'gaita',
    'guitarra', 'harpa', 'pandeiro', 'piano', 'saxofone', 'tambor', 'triângulo',
    'trompete', 'violão', 'violino',

    // Elementos Fantásticos
    'bruxa', 'dragão', 'duende', 'fada', 'fantasma', 'gigante', 'gnomo',
    'mago', 'monstro', 'princesa', 'sereia', 'unicórnio', 'vampiro', 'zumbi'
]